# accessions for samples on the SRA for PRJNA605907
SRA_accessions:
  nCoV-1: https://sra-pub-sars-cov2.s3.amazonaws.com/run/SRR11059947/SRR11059947
  nCoV-2: https://sra-pub-sars-cov2.s3.amazonaws.com/run/SRR11059946/SRR11059946
  nCoV-3: https://sra-pub-sars-cov2.s3.amazonaws.com/run/SRR11059945/SRR11059945
  nCoV-4: https://sra-pub-sars-cov2.s3.amazonaws.com/run/SRR11059944/SRR11059944
  nCoV-5: https://sra-pub-sars-cov2.s3.amazonaws.com/run/SRR11059943/SRR11059943
  nCoV-6: https://sra-pub-sars-cov2.s3.amazonaws.com/run/SRR11059942/SRR11059942
  nCoV-7: https://sra-pub-sars-cov2.s3.amazonaws.com/run/SRR11059941/SRR11059941
  nCoV-8: https://sra-pub-sars-cov2.s3.amazonaws.com/run/SRR11059940/SRR11059940

# BAM file paths on the SRA, gotten manually from links like this:
# https://trace.ncbi.nlm.nih.gov/Traces/sra/?run=SRR11059947
SRA_bams:
  nCoV-1: https://storage.googleapis.com/nih-sequence-read-archive/sra-src/SRR11059947/nCov1.bam.2
  nCoV-2: https://storage.googleapis.com/nih-sequence-read-archive/sra-src/SRR11059946/nCov2.bam
  nCoV-3: https://storage.googleapis.com/nih-sequence-read-archive/sra-src/SRR11059945/nCov3.bam
  nCoV-4: https://storage.googleapis.com/nih-sequence-read-archive/sra-src/SRR11059944/nCov4.bam
  nCoV-5: https://storage.googleapis.com/nih-sequence-read-archive/sra-src/SRR11059943/nCov5.bam
  nCoV-6: https://storage.googleapis.com/nih-sequence-read-archive/sra-src/SRR11059942/nCov6.bam
  nCoV-7: https://storage.googleapis.com/nih-sequence-read-archive/sra-src/SRR11059941/nCov7.bam
  nCoV-8: https://storage.googleapis.com/nih-sequence-read-archive/sra-src/SRR11059940/nCov8.bam

# Reference genome for alignment
refgenome: MN908947  # Wuhan-Hu-1
