name: SARS-CoV-2_Shen_et_al
channels:
  - bioconda
  - conda-forge
  - defaults

dependencies:
  - altair=4.1
  - biopython=1.79
  - fastp=0.20.1
  - ffq=0.0.4
  - ivar=1.3.1
  - jupyterlab>=3
  - mafft=7.487
  - mamba
  - minimap2=2.22
  - pandas=1.3.2
  - pip
  - plotnine>=0.8.0
  - pysam=0.16.0.1
  - python=3.9
  - samtools=1.12
  - snakemake=6.7.0
  - sra-tools=2.11.0
